---

  # Update/upgrade packages.
  # Install nodejs, npm, and pm2.
 
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: Unarchive files that are not on the EC2 instance
  ansible.builtin.unarchive:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu
    remote_src: no

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "pm2 stop default"
  become: yes
  command: pm2 stop default
  args:
    chdir: /home/ubuntu/
  ignore_errors: yes

- name: "pm2 start npm -- start"
  become: yes
  command: pm2 start npm -- start
  args:
    chdir: /home/ubuntu/
